import {StyleSheet} from 'react-native'
const stylesDetail = StyleSheet.create({
    container:{
        flex:1,
        flexDirection:'column',
        backgroundColor:'white',
    },
    imgContent:{
        flexDirection:'column', 
    },
    imgContentChild:{
        height:600,
    },
    textPrice:{
        fontSize:18,
        fontWeight:'bold',
    },
    price:{
        flexDirection:'row',
        paddingVertical:15,
        justifyContent:'space-between',
        alignItems:'center',
        paddingHorizontal:20,
        backgroundColor:'white',
    },
    priceChild:{
        flexDirection:'row',
    },
    nameShirt:{
        fontSize:17,
        color:'grey',
        paddingHorizontal:20,
        backgroundColor:'white',
        paddingBottom:15,
    },
    select:{
        backgroundColor:'white',
        marginVertical:10,
        paddingLeft:20,
    },
    selectChild:{
        borderBottomWidth:1,
        borderBottomColor:'#dedede',
        paddingVertical:15,
        paddingRight:10, 
    },
    selectChild1:{
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
    },
    selectChild2:{
        flexDirection:'row',
        alignItems:'center',
    },
    titleSelect:{
        fontSize:16,
    },
    footer:{
        flexDirection:'row',
        marginVertical:10,
    },
    colorFooter:{
        alignItems:'center',
        marginHorizontal:15,
        alignSelf:'center',
    },
    colorCartFooter:{
        fontSize:12,
        color:'black',
    },
    cartFooter:{
        alignItems:'center',
        alignSelf:'center',
        backgroundColor:'black',
        marginHorizontal:15,
    },
    textCartFooter:{
        color:'white',
        paddingHorizontal:60,
        paddingVertical:15,
        fontSize:18,
        fontWeight:'bold',
    },
    wishlistFooter:{
        alignItems:'center',
        alignSelf:'center',
        marginHorizontal:15,
    },
    
    imgContent:{},
    imgContent:{},
    imgContent:{},
});
export default stylesDetail;