import { StyleSheet} from 'react-native'
const stylesCart = StyleSheet.create({
    container:{
        flex:1,
        flexDirection:'column',
    },
    header:{
        borderBottomWidth:1,
        borderBottomColor:'#d3d3d3',
    },
    titleHeader:{
        flexDirection:'row',
        marginHorizontal:10,
        marginVertical:10,
    },
    textTitle:{
        fontSize:22,
        fontWeight:'bold',
        marginLeft:150,
    },
    nodeHeader:{
        borderBottomWidth:1,
        borderBottomColor:'#d3d3d3',
    },
    textNodeHeader:{
        textAlign:'center',
        marginVertical:20,
        fontSize:16,
        fontWeight:'bold',
        color:'gray',
    },
    content:{
        flex:1,
        flexDirection:'column',
        height:1000,
    },
    imgContent:{
        marginLeft:15,
        marginTop:20,
        flexDirection:'row',
        borderBottomWidth:1,
        borderBottomColor:'#d3d3d3',
    },
    imgContentChildStyle:{
        height:200,
        width:"30%",
        marginBottom:20,
    },
    rowPrice:{
        flex:1,
        justifyContent:'space-between',
        flexDirection:'row',
    },
    rowPriceChild:{
        flexDirection:'column',
    },
    infoImg:{
        flex:1,
        flexDirection:'column',
        marginHorizontal:15,
    },
    colorSizeInfo:{
        flexDirection:'row',
    },
    colorSizeInfoChild:{
        flex:1,
        flexDirection:'row',
        justifyContent:'space-between',
    },
    quanityInfoChild:{
        flexDirection:'row',
        marginRight:135,
        justifyContent:'space-between',
        marginBottom:20,
    },
    order:{
        backgroundColor:'#d9dadb',
        flexDirection:'column',
        
    },
    titleOrder:{
        textAlign:'center',
        fontSize:18,
        fontWeight:'bold',
        marginVertical:20,
    },
    orderChild:{
        flexDirection:'row',
        justifyContent:'space-between',
        marginHorizontal:15,
        marginVertical:5,
    },
    textSubtotalDiscount:{
        fontSize:17,
    },
    textTotal:{
        fontSize:17,
        fontWeight:'bold',
    },
    orderChild1:{
        flexDirection:'row',
        justifyContent:'space-between',
        paddingHorizontal:15,
        backgroundColor:'white',
        marginVertical:15,
    },
    textPromotionCode:{
        fontSize:19,
        fontWeight:'bold',
        paddingVertical:15,
    },
    node:{
        borderBottomWidth:1,
        borderBottomColor:'#d3d3d3',
    },
    textNodeChild:{
        textAlign:'center',
        marginVertical:15,
        fontSize:18,
        fontWeight:'bold',
    },
    textNodeChild1:{
        textAlign:'center',
        marginVertical:25,
        fontSize:16,
    },
    footer:{
        borderWidth:1,
        borderColor:'#d3d3d3',
        backgroundColor:'white',
    },
    signOut:{
        backgroundColor:'yellow',
        marginVertical:10,
        marginHorizontal:10,
    },
    textSignOut:{
        textAlign:'center',
        paddingVertical:10,
        fontSize:18,
        fontWeight:'bold',
    },
});
export default stylesCart;